keys:
  - &host_yue age1ase0m6n0w9vm2asx5katrth4j68lnm88d9tfru4q0u0qw27q5akq8ua93y
  - &host_emilia age1tcph57s2h2xz448f45fnlrw7fwakuka9xvq4fflgufpu2utjquyquphj0c
  - &host_opium age16hqvkw3yl6za6msdl76r20lf50paffqc8k3tcdjhhzgmanf6s5uq0p0msu
  - &host_trauma age1l5aerk7g40huxsnkyws0xmy89gj3852w7hnn4p00h4vgtw4j5cpqntk34s
  - &host_beryl age1l5aerk7g40huxsnkyws0xmy89gj3852w7hnn4p00h4vgtw4j5cpqntk34s
  - &host_kagamine age1mt2lsc7jhvky7ps93p5vfj66ee2s5kg7a7afas86m6nukhd9qs9s67lu8n
  - &host_miku age1wq0mn0g4eayt0909rvycu07ytrsh7zq8t69y6hse58fuldf9jqnqr9alqf

creation_rules:
  - path_regex: secrets/files/.*
    key_groups:
      - age:
        - *host_yue
        - *host_emilia
        - *host_opium
        - *host_trauma
        - *host_kagamine
        - *host_miku
  - path_regex: secrets/.*.yaml
    key_groups:
      - age:
        - *host_yue
        - *host_emilia
        - *host_opium
        - *host_trauma
        - *host_kagamine
        - *host_miku
  - path_regex: hosts/trauma/wireguard.key
    key_groups:
      - age:
        - *host_trauma
  - path_regex: secrets/nebula/.*.json
    key_groups:
      - age:
        - *host_yue
        - *host_emilia
        - *host_opium
        - *host_trauma
        - *host_kagamine
        - *host_miku

  - path_regex: hosts/yue/nebula/.*.json
    key_groups:
      - age:
        - *host_yue

  - path_regex: hosts/opium/nebula/.*.json
    key_groups:
      - age:
        - *host_yue
        - *host_opium

  - path_regex: hosts/trauma/nebula/.*.json
    key_groups:
      - age:
        - *host_yue
        - *host_trauma

  - path_regex: hosts/kagamine/nebula/.*.json
    key_groups:
      - age:
        - *host_yue
        - *host_kagamine

  - path_regex: hosts/miku/nebula/.*.json
    key_groups:
      - age:
        - *host_yue
        - *host_miku

  - path_regex: containers/*/.*
    key_groups:
      - age:
        - *host_yue
        - *host_trauma
        - *host_kagamine
        - *host_miku
