keys:
  - &host_yue age1ase0m6n0w9vm2asx5katrth4j68lnm88d9tfru4q0u0qw27q5akq8ua93y
  - &host_emilia age1tcph57s2h2xz448f45fnlrw7fwakuka9xvq4fflgufpu2utjquyquphj0c

creation_rules:
  - path_regex: secrets/.*.yaml
    key_groups:
      - age:
        - *host_yue
        - *host_emilia
