# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ata_piix" "uhci_hcd" "xen_blkfront" "vmw_pvscsi"];
  boot.kernelModules = ["nvme"];
  boot.initrd.kernelModules = [];
  boot.extraModulePackages = [];

  boot.loader.grub = {
    enable = true;
    # It breaks sometimes
    # devices = ["/dev/vda"];
    devices = ["/dev/sda"];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ce1e50b7-51ad-4707-a483-8003a82ef2a1";
    fsType = "xfs";
  };

  swapDevices = [];
}
